services:
  socat:
    image: alpine/socat
    container_name: socat_container
    restart: always
    ports:
      - "127.0.0.1:2375:2375"
    networks:
      - jenkins
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    entrypoint: ["socat", "tcp-listen:2375,fork,reuseaddr", "unix-connect:/var/run/docker.sock"]

networks:
  jenkins:
    external: true
